import React, { useEffect, useState } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const ExaAI = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate loading time
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1 pt-24 pb-12">
        <div className="container mx-auto px-4 md:px-6 max-w-6xl">
          <div className="mb-6">
            <Link to="/ai-search" className="inline-flex items-center text-school-blue hover:text-school-yellow transition-all">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to AI Search Tools
            </Link>
          </div>

          <div className="flex justify-between items-center mb-4">
            <h1 className="text-3xl font-bold">Exa AI Chat</h1>
            <button
              onClick={() => window.open('https://chat.exa.ai', '_blank')}
              className="text-sm text-school-blue hover:text-school-yellow transition-all flex items-center"
            >
              Open in new tab
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 ml-1" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
              </svg>
            </button>
          </div>
          <p className="text-gray-600 mb-4">
            Advanced AI chat with web search capabilities for accurate, up-to-date information and research assistance.
          </p>

          <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-gray-200 h-[80vh] flex flex-col">
            {isLoading ? (
              <div className="flex-1 flex items-center justify-center">
                <div className="flex flex-col items-center">
                  <div className="w-16 h-16 border-4 border-school-blue border-t-transparent rounded-full animate-spin"></div>
                  <p className="mt-4 text-gray-600">Loading Exa AI Chat...</p>
                </div>
              </div>
            ) : (
              <iframe
                src="https://chat.exa.ai"
                title="Exa AI Chat"
                className="w-full h-full border-0"
                allow="microphone; camera; geolocation; clipboard-read; clipboard-write; fullscreen"
                sandbox="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-downloads allow-modals"
              />
            )}
          </div>

          <div className="mt-4 p-4 bg-blue-50 rounded-lg border border-blue-100">
            <p className="text-sm text-gray-600">
              <strong>Note:</strong> Exa AI Chat is provided as an external service. Golden Gate Int. School is not responsible for the content generated by this tool.
              Always verify information from multiple sources and use critical thinking when evaluating AI-generated content.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default ExaAI;
