import React, { useEffect, useState } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const ExaAI = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate loading time
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1 pt-24 pb-12">
        <div className="container mx-auto px-4 md:px-6 max-w-6xl">
          <div className="mb-6">
            <Link to="/ai-search" className="inline-flex items-center text-school-blue hover:text-school-yellow transition-all">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to AI Search Tools
            </Link>
          </div>

          <h1 className="text-3xl font-bold mb-4">Exa AI Chat</h1>
          <p className="text-gray-600 mb-8">
            Advanced AI chat with web search capabilities for accurate, up-to-date information and research assistance.
          </p>

          <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-gray-200 h-[70vh] flex flex-col">
            {isLoading ? (
              <div className="flex-1 flex items-center justify-center">
                <div className="flex flex-col items-center">
                  <div className="w-16 h-16 border-4 border-school-blue border-t-transparent rounded-full animate-spin"></div>
                  <p className="mt-4 text-gray-600">Loading Exa AI Chat...</p>
                </div>
              </div>
            ) : (
              <iframe
                src="https://chat.exa.ai"
                title="Exa AI Chat"
                className="w-full h-full border-0"
                allow="microphone; camera; geolocation"
              />
            )}
          </div>

          <div className="mt-8 bg-gray-50 rounded-lg p-6">
            <h2 className="text-xl font-semibold mb-4">About Exa AI Chat</h2>
            <p className="text-gray-700 mb-4">
              Exa AI Chat is a powerful AI assistant that combines the capabilities of large language models with real-time web search. 
              This allows it to provide up-to-date information and accurate answers to your questions.
            </p>
            <h3 className="text-lg font-medium mb-2">Key Features:</h3>
            <ul className="list-disc pl-5 space-y-2 text-gray-700">
              <li>Real-time web search capabilities</li>
              <li>Accurate citations and sources for information</li>
              <li>Advanced reasoning and explanation abilities</li>
              <li>Support for academic research and homework help</li>
              <li>User-friendly interface with conversation history</li>
            </ul>
            <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-100">
              <p className="text-sm text-gray-600">
                <strong>Note:</strong> Exa AI Chat is provided as an external service. Golden Gate Int. School is not responsible for the content generated by this tool. 
                Always verify information from multiple sources and use critical thinking when evaluating AI-generated content.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default ExaAI;
